version: 2
jobs:
  build:
    working_directory: /go/src/github.com/johnliu8365/GetJsonAPI
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag getjsonapi_getjsonapi $DOCKER_HUB_USER_ID/getjsonapi:$CIRCLE_SHA1
            docker tag getjsonapi_getjsonapi $DOCKER_HUB_USER_ID/getjsonapi:latest
            docker push $DOCKER_HUB_USER_ID/getjsonapi:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/getjsonapi:latest